### ISSUE TITLE
Rebase to universal ctags

### ISSUE THREAD

**Issue by masatake** [arduino/ctags#2]
Hi,

I found this project today. I'm a co-developer of universal-ctags.
It seems that this repository is forked from exuberant-crags.
Instead, how about forking from universal-ctags?
The development of universal-ctags is more active than exuberant-crags.

Please, viist https://ctags.io if you have an interest.

Regards,
Masatake YAMATO

**Comment by ffissore** [comment]
Thanks @masatake, I'm playing with it right now
